[package]
name = "artimonist-cli"
version = "0.5.1"
description = "A tool for generating mnemonics based on diagrams."
authors = ["Artimonist <artimonist@gmail.com>"]
homepage = "https://artimonist.org/"
repository = "https://github.com/artimonist/artimonist-cli/"

license = "MIT"
keywords = ["bitcoin", "mnemonic"]
categories = ["cryptography"]
rust-version = "1.84.0"
edition = "2021"

[[bin]]
name = "artimonist"
path = "src/main.rs"

[dependencies]
artimonist = "0.7.1"
clap = { version = "^4.5.28", features = ["derive"] }
inquire = "0.7.5"
comfy-table = "7.1.3"
# serde_json = "1.0.138"
# dialoguer = "0.11.0"
# unicode-width = "0.2.0"
