[package]
name = "artimonist-cli"
version = "0.10.0"
description = "A tool for generating mnemonics based on diagrams."
authors = ["Artimonist <artimonist@gmail.com>"]
homepage = "https://artimonist.org/"
repository = "https://github.com/artimonist/artimonist-cli/"

license = "MIT"
keywords = ["bitcoin", "mnemonic"]
categories = ["cryptography"]
rust-version = "1.85.0"
edition = "2024"

[[bin]]
name = "artimonist"
path = "src/main.rs"

[dependencies]
artimonist = { version = "0.11.2", features = ["multilingual", "testnet"] }
clap = { version = "^4.5.28", features = ["derive"] }
inquire = { version = "^0.7.5", default-features = false, features = ["crossterm"] }
comfy-table = { version = "^7.1.3", default-features = false }
thiserror = "2.0.11"
bip38 = "1.1.1"
# crossterm = "0.28.1"
# serde_json = "1.0.138"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
