[package]
name = "artimonist-cli"
version = "0.1.0"
description = "A tool for generating mnemonics based on diagrams."
authors = ["Artimonist <artimonist@gmail.com>"]
homepage = "https://artimonist.org/"
repository = "https://github.com/artimonist/artimonist-cli/"

keywords = ["bitcoin", "mnemonic"]
categories = ["cryptography"]
rust-version = "1.78.0"
edition = "2021"

[dependencies]
artimonist = "0.3.5"
clap = { version = "^4.5.26", features = ["derive", "unicode"] }
