[package]
name = "artimonist-cli"
version = "0.9.2"
description = "A tool for generating mnemonics based on diagrams."
authors = ["Artimonist <artimonist@gmail.com>"]
homepage = "https://artimonist.org/"
repository = "https://github.com/artimonist/artimonist-cli/"

license = "MIT"
keywords = ["bitcoin", "mnemonic"]
categories = ["cryptography"]
rust-version = "1.84.0"
edition = "2021"

[[bin]]
name = "artimonist"
path = "src/main.rs"

[dependencies]
artimonist = { version = "0.8.2", features = ["multilingual"] }
clap = { version = "^4.5.28", features = ["derive"] }
inquire = { version = "^0.7.5", default-features = false, features = ["crossterm"] }
comfy-table = { version = "^7.1.3", default-features = false }
thiserror = "2.0.11"
# crossterm = "0.28.1"
# serde_json = "1.0.138"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
